<!DOCTYPE html PUBLIC “-//W3C//DTD XHTML 1.1//EN” “http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd”>
<?php
$variable1="PHP5";
?>
<htmlxmlns="http://www.w3.org/1999/xhtml"xml:lang=“es">
<head>
<metahttp-equiv="Content-Type"content="text/html;charset=UTF-8"/>
<?php
echo"<title>UnapaginallenadescriptsPHP</title>";
?>
</head>
<body>
<scriptlanguage="php">←(3)
echo"<h1>BUENODIASATODOS</h1>";
</script>
<?php
echo"<h2>TituloescritoporPHP</h2>";
$variable2="MySQL";
?>
<p>Vasadescubrir<?=$variable1?>←(5)</p>
<?php
echo"<h2>Buenosdíasde$variable1</h2>";
?>
<p>UtilizacióndevariablesPHP<br/>Vasadescubririgualmente
<?php
echo$variable2;
?>
</p>
<?="<div><big>Buenosdíasde$variable2</big></div>"?>←(8)
</body>