<hr/>
<?php
echo"<div><h1style=\"border-width:3;border-style:groove;background-color:
#ffcc99;\">FinaldelapáginaPHPVínculosútiles:<ahref=\"php.net\">php.net</a>
&nbsp;<ahref=\"mysql.org\">mysql.org</a></h1>";
echo"Nombredelarchivoejecutado:",$_SERVER['PHP_SELF'],"&nbsp;&nbsp;&nbsp;";
echo"Nombredelarchivoincluido:",__FILE__,"</div>";
?>
</body>
</html>